version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: meal_postgres
    environment:
      POSTGRES_DB: meal_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: