
services:
# service 1: FastAPI web app
  api:
    build: .
    container_name: meal_api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=meal_db
      - DB_USER=my_user
      - DB_PASSWORD=my_password
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_started

# service 2: PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: meal_postgres
    environment:
      POSTGRES_DB: meal_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: